language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - poetry install

before_install:
  - pip install poetry

jobs include:
  - name: tests
    script: poetry run pytest tests/
